Fix incorrect template element xml serialization
jhy/jsoup pull request #1391
Opened 2020-05-30 12:57 UTC by Tricker-z

Fix #1315 

After parsing the HTML fragment, the inner start/end tags is included.

2020-12-08 15:57 UTC, bartektartanus requested changes

2020-12-08 15:57 UTC, bartektartanus commented on src/test/java/org/jsoup/parser/TemplateTest.java
> +        System.out.println(doc.outerHtml());
All `println` should be removed from tests.

2020-12-08 15:57 UTC, bartektartanus commented on src/test/java/org/jsoup/parser/TemplateTest.java
> +        assertEquals("<html><head></head><body><template id=\"lorem-ipsum\">\n" +
Maybe instead of checking HTML literally you should verify that `doc.body()` is `template` tag and has two `td` tags as children?

2020-12-08 15:57 UTC, bartektartanus commented on src/main/java/org/jsoup/parser/TemplateTest.java
> +package org.jsoup.parser;
This test is duplicated and also added to `src` instead of `test`. Remove this.

2020-12-08 15:57 UTC, bartektartanus commented on src/test/java/org/jsoup/parser/TemplateTest.java
> +    public void parseXml() {
This test does not verify anything. Add some assertions or remove it.

2021-09-17 09:34 UTC, jhy commented
Thanks for this, and sorry for the late reply! I have implemented a similar change, aligned to the HTML5 spec, in #1634.

2021-09-17 09:34 UTC, closed without merging