Avoid the term whitelist
jhy/jsoup pull request #1423
Opened 2020-08-19 19:55 UTC by nkiesel

This term was replaced with allowedList. See e.g. https://tools.ietf.org/id/draft-knodel-terminology-00.html
for a rationale.

2020-08-20 07:56 UTC, drei01 commented
This looks good to me, thanks for picking up on my original request.

2020-10-14 14:35 UTC, drei01 commented
Any updates on this PR?

2020-12-10 12:24 UTC, jhy commented
Thanks, will plan to get this in for 1.14.1.

2020-12-11 00:01 UTC, jhy requested changes
Thanks for this - general approach is good but please see notes around preserving the file change history, and not duplicating the entire test files redundantly.

2020-12-11 00:01 UTC, jhy commented on src/test/java/org/jsoup/safety/CleanerDeprecatedTest.java
> +package org.jsoup.safety;
Per other test comment, this should not be an entire redundant copy. Just the deprecated names.

2020-12-11 00:03 UTC, jhy commented
I am happy to make the noted changes BTW, LMK.

2020-12-15 08:20 UTC, jhy commented
Thanks - rolled this mostly in to #1464 with a few minor changes (called it Safelist, mainly)

2020-12-15 08:20 UTC, closed without merging