Proposed fix : Disallow replacing nodes with themselves
jhy/jsoup pull request #1844
Opened 2022-09-22 01:11 UTC by jdngray77

fixes #1838 : `Node.replaceWith` creates an invalid state if a node is replaced with itself.

Proposed changes :
 * Equality validation, throw a `ValidationException` just as any other invalid parameter would.
 * Unit test for edge case

2022-09-24 16:14 UTC, FanJups commented
Thanks for this correction 💯

2022-09-24 16:23 UTC, jdngray77 commented
My apologies, I typed the wrong issue number - this is unrelated to your problem of self closing tags.

2022-09-24 16:27 UTC, FanJups commented
all right lol

2023-01-05 01:29 UTC, jhy commented on src/main/java/org/jsoup/helper/Validate.java
> +    public static void notStrictlyEqual(Object a, Object b, String message) {
Personally, I would call this method something like "NotSameObject". To make it clearer that it's an identity check.

2023-01-05 01:33 UTC, jhy commented
Thanks for the PR and the bug report.

I think that it would be better to make this a no-op vs a validation error. It follows closer to the developer's intent (whatever that was) and is not surprising. 

I.e., if `(this == in) return`

2023-01-06 08:47 UTC, jhy requested changes
As noted inline -- would be better if it was a no-op vs a Validation Error.

2023-01-19 06:01 UTC, jhy commented
I implemented this with 9bb07d2ab43c0377806b4bb7b88c64366a39a469

2023-01-19 06:01 UTC, closed without merging